### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'pyrsgis'


### ISSUE THREAD

**Issue by lindauju** [aishwaryahegde29/RasterTool_Qgis#4]
Konnte Erweiterung 'rastertool' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/lindauju/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rastertool\__init__.py", line 35, in classFactory
    from .RasterTool import RasterTool
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/lindauju/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rastertool\RasterTool.py", line 54, in <module>
    from pyrsgis.convert import rastertocsv
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyrsgis'

```
rastertool 0.2, QGIS 3.10.5-A Coruña on Windows 10

**Comment by carminemassarelli** [comment]
I changed from
from matplotlib.mlab import griddata
to
from scipy.interpolate import griddata and it works again for what I need.

**Comment by abdulhafidz6** [comment]
I got the same issue and resolved

first I follow @carminemassarelli suggestion, it is in RasterTool.py file in Raster Tool folder plugin. 
Change matplotlib.mlab into scipy.interpolate (LN 67)
then change plotly.plotly into chart_studio.plotly (LN 70)

you'll be asked to install visvis package through OSGEO4W shell
Restart QGIS.

Good Luck!
